### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by kardwen** [lennart-finke/kakikun#6]
Initially my build failed because of mismatched libc dependencies, so I deleted Cargo.lock and ran `cargo update` which solved this issue.

```
~/Documents/rust/kakikun/ cargo build --release
    Updating crates.io index
error: failed to select a version for `libc`.
    ... required by package `mio v0.8.11`
    ... which satisfies dependency `mio = "^0.8"` (locked to 0.8.11) of package `crossterm v0.25.0`
    ... which satisfies dependency `crossterm = "^0.25"` (locked to 0.25.0) of package `cursive v0.20.0`
    ... which satisfies dependency `cursive = "^0.20"` (locked to 0.20.0) of package `kakikun v0.1.0 (/home/felix/Documents/rust/kakikun)`
versions that meet the requirements `^0.2.149` are: 0.2.159, 0.2.158, 0.2.157, 0.2.156, 0.2.155, 0.2.153, 0.2.152, 0.2.151, 0.2.150, 0.2.149

all possible versions conflict with previously selected packages.

  previously selected package `libc v0.2.140`
    ... which satisfies dependency `libc = "^0.2"` (locked to 0.2.140) of package `cursive v0.20.0`
    ... which satisfies dependency `cursive = "^0.20"` (locked to 0.20.0) of package `kakikun v0.1.0 (/home/felix/Documents/rust/kakikun)`

failed to select a version for `libc` which could resolve this conflict
```

The error may be related to my musl libc version of Alpine Linux.

I am not familiar with the Rust build system so I'm not sure what to do here and if the Cargo.lock file is needed.

**Comment by lennart-finke** [comment]
Hello, thanks so much for trying the software! Since writing this I have gained the ability to test on Mac, and get the same error there. No idea what is going on, but I think it does make sense not to include the Cargo.lock (despite what I had heard a few years back, that including Cargo.lock makes for reproducible binary builds). Have a nice day!

**Comment by kardwen** [comment]
<https://blog.rust-lang.org/2023/08/29/committing-lockfiles.html>
Apparently they have changed their guideline last year. Thanks!
